import Head from 'next/head'
import Image from 'next/image'
import dynamic from 'next/dynamic';
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useWallet, useConnection } from '@solana/wallet-adapter-react';
import Transfer from 'components/transfer';

const inter = Inter({ subsets: ['latin'] })
const WalletDisconnectButtonDynamic = dynamic(
  async () => (await import('@solana/wallet-adapter-react-ui')).WalletDisconnectButton,
  { ssr: false }
);
const WalletMultiButtonDynamic = dynamic(
  async () => (await import('@solana/wallet-adapter-react-ui')).WalletMultiButton,
  { ssr: false }
);

export default function Home() {
  
  const {publicKey, sendTransaction} = useWallet();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://solana.com/">Solana!</a>
        </h1>

        <div className={styles.walletButtons}>
          {!publicKey ?
            <WalletMultiButtonDynamic />
            :
            <WalletDisconnectButtonDynamic />
          }
          </div>

        <Transfer/>

      </main>
    </>
  )
}
